---
apiVersion: punchline.gitlab.thalesdigital.io/v1
kind: Stormline
metadata:
  name: input-example-storm
spec:  
  image: ghcr.io/punchplatform/stormline:7.0.1-SNAPSHOT
  initContainerImage: ghcr.io/punchplatform/resourcectl:7.0.1-SNAPSHOT
  initContainerUrl: http://artifacts-service.punch-gateway-ns:4245
  dependencies:
  - additional-punch-jar:org.thales.punch:punch-storm-node-starter-kit:1.0.0
  punchline:
    dag:
    - type: input_node
      component: input_node
      package: org.thales.punch.storm.node.starter.kit
      settings:
        user_name: alice
        load_control: rate
        load_control.rate: 1
      publish:
        - stream: logs
          fields:
            - log
    - type: punchlet_node
      settings:
        punchlet_code: "{print(root);}"
      component: punch_bolt
      subscribe:
      - component: input_node
        stream: logs
      publish: []