---
apiVersion: punchline.punchplatform.io/v2
kind: BatchPunchline
metadata:
  name: punchline-java
spec:
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-java:8.1-dev
      imagePullPolicy: IfNotPresent
      env:
        - name: JDK_JAVA_OPTIONS
          value: "-Xms100m -Xmx450m"
  dag:
    - id: generator
      kind: source
      type: generator_source
      settings:
        messages_size: 3
        messages:
          - My 1st log
          - My 2nd message log
          - And finally a 3rd one
      out:
        - id: punchlet
          table: logs
          columns:
            - name: log
              type: string
    - id: punchlet
      kind: function
      type: punchlet_function
      settings:
        punchlets: 
          - "{ print(root); }"