# The Punchplatform code is licensed under the outer restricted Tiss license:
#
#   Copyright © [2014]-[2021] Thales Services
#
#   Licensed under the Thales Inner Source Software License
#   (Version 1.0, InnerPublic - OuterRestricted the "License");
#   You may not use this file except in compliance with the License.
#
#   You may obtain a copy of the License at https://ecm.corp.thales/Livelink/livelink.exe?func=ll&objId=126019196&objAction=browse&viewType=1
#
#   See the License for the specific language governing permissions and limitations
#   under the License.

FROM ghcr.io/punchplatform/stormline:7.0.1-SNAPSHOT

WORKDIR /resources
COPY punchlets .
COPY punchline .

WORKDIR /