apiVersion: apps/v1
kind: Deployment
metadata:
  name: punchline
  labels:
    app: punch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: punch
  template:
    metadata:
      labels:
        app: punch
    spec: 
      containers:
        - name: punchline
          image: ghcr.io/punchplatform/punchline:latest
          imagePullPolicy: Always
          args: ["-t", "default", "start", "-p", "resources/kafka_punchlet.yaml"]