#!/usr/bin/env bash -ec -o pipefail

###
# User Configuration
###

# Information used to generate metadata.yml
GROUP_ID ?= io.github.starter
ARTIFACT_ID ?= elastalert-modules
VERSION ?= 1.0.0

###
# internal
###

# Build
BUILD_CONTAINER ?= build_container
BUILD_IMG ?= build-image
BUILD_TIMESTAMP = $(shell date +%s)

# Output files
OUTPUT_DIR = $(CURDIR)/target
OUTPUT_METADATA = $(OUTPUT_DIR)/metadata.yml
OUTPUT_FILE = $(OUTPUT_DIR)/$(ARTIFACT_ID)-$(VERSION).pex
OUTPUT_ARCHIVE = $(OUTPUT_DIR)/$(ARTIFACT_ID)-$(VERSION).zip

# Python
VENV = $(CURDIR)/.venv-poetry
PIP = $(VENV)/bin/pip
POETRY = $(VENV)/bin/poetry
PEX = $(VENV)/bin/pex

# Run
ELASTALERT_IMG ?= ghcr.io/punchplatform/punch-elastalert:8.0-dev
TEST_DIR= $(CURDIR)/tests/custom_test

# Upload
ARTIFACT_SERVER_UPLOAD_URL ?= http://172.19.0.2:4245/v1/artifacts/upload