---
apiVersion: punchline.punchplatform.io/v2
kind: SparkPunchline
metadata:
  name: punchline-pyspark
spec:
  containers:
    serviceAccount: admin-user
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-pyspark:8.1-dev
      imagePullPolicy: IfNotPresent
  engineSettings:
    spark.hadoop.fs.s3a.access.key: "minio"
    spark.hadoop.fs.s3a.aws.credentials.provider: "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    spark.hadoop.fs.s3a.endpoint: "http://minio.object-store:9002"
    spark.hadoop.fs.s3a.path.style.access: "True"
    spark.hadoop.fs.s3a.secret.key: "password"
  dag:
    - id: elastic
      kind: source
      type: elasticsearch
      settings:
        http_hosts:
        - host: punchplatform-es-default.doc-store
          port: 9200
          scheme: http
        index: index-pyspark
        security:
          credentials:
            password: elastic
            username: elastic
      out:
        - id: sql
          table: table

    - id: kafka
      kind: source
      type: kafka
      settings:
        kafka.bootstrap.servers: kafka-kafka-bootstrap.processing:9092
        topic: topic-pyspark
      out:
        - id: sql
          table: table

    - id: minio_csv
      kind: source
      type: file
      settings:
        format: csv
        options:
          header: true
        path: s3a://default/pyspark/csv
      out:
        - id: sql
          table: table

    - id: minio_json
      kind: source
      type: file
      settings:
        format: json
        path: s3a://default/pyspark/json
      out:
        - id: sql
          table: table

    - id: minio_parquet
      kind: source
      type: file
      settings:
        format: parquet
        path: s3a://default/pyspark/parquet
      out:
        - id: sql
          table: table

    - id: sql
      kind: function
      type: sql
      settings:
        statements:
        - statement: SELECT count(*) FROM elastic_table
          output_table_name: elastic_result
        - statement: SELECT * FROM kafka_table
          output_table_name: kafka_result
        - statement: SELECT * FROM minio_csv_table
          output_table_name: minio_csv_result
        - statement: SELECT * FROM minio_json_table
          output_table_name: minio_json_result
        - statement: SELECT * FROM minio_parquet_table
          output_table_name: minio_parquet_result
      out:
        - id: print
          #multi tables?
          table: elastic_result
        - id: print
          table: kafka_result
        - id: print
          table: minio_csv_result
        - id: print
          table: minio_json_result
        - id: print
          table: minio_parquet_result

    - id: print
      kind: sink
      type: show 
      settings:
        num_rows: 10