apiVersion: punchline.punchplatform.io/v2
kind: BatchPunchline
metadata:
  name: mypunchline
spec:
  dag:
    - id: input
      kind: source
      type: generator_source
      exit_conditions:
        failure:
          fails_greater_or_equal_to: 1
      settings:
        expectation: none
        acked:
        messages:
          - "5.23.164.1"
      out:
        - id: parser
          table: logs
          columns:
            - name: log
              type: string
    - id: parser
      type: punchlet_function
      kind: function
      settings:
        resources:
          - type: file
            format: geoipv4
            url: /files/belgium4.csv.gz
          - type: file
            format: geoipv6
            url: /files/belgium6.csv.gz
        punchlets:
          - /files/punchlet.punch
      out:
        - id: print
          table: logs
          columns:
            - name: log
              type: string
            - name: doc
              type: string
    - id: print
      type: punchlet_function
      kind: function
      settings:
        punchlets: 
        - "{print(root);}"
