[tool.poetry]
name = "custom_nodes"
# managed by makefile
version = "0.0.0"
description = ""
authors = ["Punch"]

[tool.poetry.dependencies]
python = "^3.10.4"

[tool.poetry.dev-dependencies]
punch-api = "8.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.core.masonry.api"
