[tool.poetry]
name = "custom_node"
version = "1.0.0"
description = ""
authors = ["RT"]

[tool.poetry.dependencies]
python = "^3.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
