apiVersion: punchline.punchplatform.io/v2
kind: StreamPunchline
metadata:
  name: my-parser
spec:  
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-java:8.0-dev
    resourcesInitContainer:
      image: ghcr.io/punchplatform/resourcectl:8.0-dev
      resourcesProviderUrl: http://artifacts-server.punch-artifacts:4245
  dependencies:
    - punch-parsers:com.mycompany:parsers:1.0.0
  dag:
  - id: input
    kind: source
    type: syslog_source
    settings:
      host: 0.0.0.0
      port: 9902
    out: 
    - id: parser
      table: logs
      columns:
      - name: data
        type: string
  - id: parser
    type: punchlet_function
    kind: function
    settings:
      resources:
      - name: color_codes
        format: json
        type: file
        url: com/mycompany/sample/resources/color_codes.json
      - name: custom_groks
        type: file
        format: grok
        url: com/mycompany/sample/groks
      punchlets:
      - com/mycompany/sample/parser.punch
    out: 
    - id: print
      table: logs
      columns:
      - name: log
        type: string
  - id: print
    type: punchlet_function
    kind: function
    settings:
      punchlet_code: "{print(root);}"