apiVersion: punchline.gitlab.thalesdigital.io/v2
kind: StreamPunchline
metadata:
  name: my-parser
spec:  
  initContainerImage: ghcr.io/punchplatform/resourcectl:8.0-dev
  initContainerUrl: http://artifacts-service.kooker:4245
  image: ghcr.io/punchplatform/punchline-java:8.0-dev
  dag:
  - id: input
    kind: source
    type: syslog_source
    settings:
      host: 0.0.0.0
      port: 9902
    out: 
    - id: parser
      table: logs
      columns:
      - name: log
        type: string
  - id: parser
    type: punchlet_function
    kind: function
    settings:
      json_resources:
      - com/mycompany/sample/resources/color_codes.json
      punchlet_grok_pattern_dirs:
      - com/mycompany/sample/groks/
      punchlets:
      - com/mycompany/sample/parser.punch