---
apiVersion: punchline.punchplatform.io/v2
kind: BatchPunchline
metadata:
  name: punchline-python
spec:
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-python:8.0-dev
      imagePullPolicy: IfNotPresent
      env:
        - name: JDK_JAVA_OPTIONS
          value: "-Xms100m -Xmx450m"
  dag:
    - id: input
      kind: source
      type: generator_source
      settings:
        messages:
          - [ 0.8 , 1.8 ]
          - [ 0.0 , 1.0 ]
          - [ 3.5 ,  4.5 ]
          - [ 7.2 ,  8.2 ]
          - [ 0.6 , 1.6 ]
          - [ 2.5 ,  3.5 ]
          - [ 7.9 ,  8.9 ]
          - [ 0.0 , 1.0 ]
          - [ 2.9 ,  3.9 ]
          - [ 8.0 ,  2.9 ]
      out:
        - id: print_all
        - id: print
          table: data
          columns:
            - name: 1
              type: float

    - id: print_all
      kind: sink
      type: show_sink

    - id: print
      kind: sink
      type: show_sink
      settings:
        title: "Showing the column 1:"