---
apiVersion: scheduler.punchplatform.io/v2
kind: Plan
metadata:
  name: plan-spark-punchline
spec:
  kind: SparkPunchline
  interval: 10s
  checkpointRef:
    name: plan-spark-punchline-checkpoint
    kind: ConfigMap
  #cron: "* * * * *"
  dates:
    from:
      offset: "-10h45m"
      format: "2006-01-02T15:04:05-0700"
  templateSpec:
    containers:
      serviceAccount: admin-user
      applicationContainer:
        image: ghcr.io/punchplatform/punchline-spark:8.1-dev
        imagePullPolicy: IfNotPresent
    jobSettings:
      backoffLimit: 10
    dag:
    - id: input
      kind: source
      type: generator
      settings:
        messages:
          - name: phil
            age: 21
            host: host%{cnt}
            time: "{{ .from }}"
        messages_size: 10
        counter_tag: "%{cnt}"
      out:
        - id: output

    - id: output
      kind: sink
      type: show