apiVersion: punchline.punchplatform.io/v2
kind: BatchPunchline
metadata:
  name: mypunchline
spec:
  dag:
    - id: input
      kind: source
      type: generator_source
      exit_conditions:
        failure:
          fails_greater_or_equal_to: 1
      settings:
        expectation: none
        acked:
        messages:
          - "red"
      out:
        - id: parser
          table: logs
          columns:
            - name: log
              type: string
    - id: parser
      type: punchlet_function
      kind: function
      settings:
        resources:
          - name: color_codes
            url: /files/color_codes.json
            type: file
            format: json
        punchlets:
          - /files/punchlet.punch
      out:
        - id: print
          table: logs
          columns:
            - name: log
              type: string
            - name: color
              type: string
    - id: print
      type: punchlet_function
      kind: function
      settings:
        punchlets: 
        - "{print(root);}"
