apiVersion: punchline.punchplatform.io/v2
kind: StreamPunchline
metadata:
  name: mypunchline
spec:
  dag:
  - id: input
    kind: source
    type: generator_source
    exit_conditions:
     success:
        acks_greater_or_equal_to: 1
        require_no_remaining_row_to_inject: true
        require_no_pending_row: true
     failure:
        fails_greater_or_equal_to: 1
    settings:
      expectation: none
      acked:
      messages:
        - "red"
    out:
    - id: parser
      table: logs
      columns:
      - name: log
        type: string
  - id: parser
    type: punchlet_function
    kind: function
    settings:
      resources:
      - name: color_codes 
        url: /color_codes.json
        type: file
        format: json
      punchlets:
      - /punchlet.punch
    out:
    - id: print
      table: logs
      columns:
      - name: log
        type: string
      - name: color
        type: string
  - id: print
    type: punchlet_function
    kind: function
    settings:
      punchlet_code: "{print(root);}"
