---
apiVersion: punchline.gitlab.thalesdigital.io/v2
kind: SparkPunchline
metadata:
  name: input-example-spark
spec:
  containers:
    serviceAccount: admin-user
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-spark:8.0-dev
      imagePullPolicy: IfNotPresent
    resourcesInitContainer:
      image: ghcr.io/punchplatform/resourcectl:8.0-dev
      resourcesProviderUrl: http://artifacts-service.default:4245
      debug: true
  dependencies:
    - additional-spark-jar:io.github.starters:punchline-spark-starter-kit:1.0.0
  engineSettings:
    spark.kubernetes.authenticate.driver.serviceAccountName: admin-user
    spark.additional.jar: punchline-spark-starter-kit-1.0.0-jar-with-dependencies.jar
  dag:
    - id: input
      type: io.github.starter.punchline.spark.CustomSource
      kind: source
      settings:
        title: name
        input_data:
          - alice
          - bob
          - john
      out:
        - id: select

    - id: select
      type: io.github.starter.punchline.spark.CustomFunction
      kind: function
      settings:
        select:
          - name
      out:
        - id: show

    - id: show
      type: io.github.starter.punchline.spark.CustomSink
      kind: function
      settings:
        truncate: 3