---
# Service to receive logs at input point of ltr

apiVersion: v1
kind: Service
metadata:
  name: lmr-input-service
  namespace: mytenant
spec:
  ports:
    - port: 9990
      targetPort: 9990
      name: lmr-input-service
  selector:
    stormline-owner: lmr-in
