---
apiVersion: 1.0
kind: PunchletGroup
metadata:
  name: "sample group of related punchlets"
spec:
  resources:
    - name: custom_groks
      type: file
      format: grok
      url: groks/pattern.grok
    - name: standard_groks
      type: file
      format: grok
      url: /usr/share/punch/resources/patterns
    - name: color_codes
      type: file
      format: json
      url: resources/color_codes.json
  punchlets:
    - punchlet: parser.punch
      labels:
        description: "a sample punchlet for you to easily start coding your own"
        performance: 3000
        category: sample
        author: "punch team"
        vendor: punchplatform
      inputStream:
        - name: logs
          fields:
            - name: data
              type: string
    - punchlet: enrich.punch
      labels:
        description: "a sample punchlet to illustrate chaining and enrichment concepts"
        performance: 2000
        category: sample
        author: "punch team"
        vendor: punchplatform
