apiVersion: punchline.gitlab.thalesdigital.io/v2
kind: StreamPunchline
metadata:
  name: mypunchline
spec:
  dependencies:
    - punch-parsers:io.github.punchplatform:punch-sample-parser:8.0.0
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-starter:latest
  dag:
  - id: input
    kind: source
    type: generator_source
    exit_conditions:
     success:
        acks_greater_or_equal_to: 1
        require_no_remaining_row_to_inject: true
        require_no_pending_row: true
     failure:
        fails_greater_or_equal_to: 1
    settings:
      expectation: none
      acked:
      messages:
        - "GET_100"
    out:
    - id: parser
      table: logs
      columns:
      - name: log
        type: string
  - id: parser
    type: punchlet_function
    kind: function
    settings:
      resources:
      - name: taxonomy 
        url: io/github/punchplatform/sample/taxonomy.json
        type: file
        format: json
      punchlets:
      - io/github/punchplatform/sample/punchlet.punch
    out:
    - id: print
      table: logs
      columns:
      - name: log
        type: string
      - name: taxonomy
        type: string
  - id: print
    type: punchlet_function
    kind: function
    settings:
      punchlet_code: "{print(root);}"
