apiVersion: punchline.gitlab.thalesdigital.io/v2
kind: StreamPunchline
metadata:
  name: mypunchline
spec:
  dag:
  - id: input
    kind: source
    type: generator_source
    exit_conditions:
     success:
        acks_greater_or_equal_to: 10
        require_no_remaining_row_to_inject: true
        require_no_pending_row: true
     failure:
        fails_greater_or_equal_to: 1
    settings:
      message_count: 10
      interval: 0
      messages:
        - logs:
            log: "log %{message_num}"
            _ppf_id: "uuid%{message_num}"
            _ppf_timestamp: 18722782
            _ppf_local_host: 127.0.0.1
            _ppf_local_port: 9888
            _ppf_remote_host: 5.145.111.23
            _ppf_remote_port: 37632
    out:
    - id: print
      table: logs
      columns:
       - name: log
         type: string
       - name: _ppf_id
         type: string
       - name: _ppf_timestamp
         type: long
       - name: _ppf_local_host
         type: string
       - name: _ppf_local_port
         type: int
       - name: _ppf_remote_host
         type: string
       - name: _ppf_remote_port
         type: int
  - id: print
    type: punchlet_function
    kind: function
    settings:
      punchlet_code: "{print(root);}"

