apiVersion: punchline.punchplatform.io/v2
kind: BatchApplicationModel
metadata:
  name: appmodel
spec:
  templateSpec:
    jobSettings:
      backoffLimit: 0
      ttlSecondsAfterFinished: 5
    containers:
      applicationContainer:
        image: busybox
        env:
          - name: JDK_JAVA_OPTIONS
            value: "-Xms100m -Xmx450m"
        command:
          - "/bin/sh"
          - "-c"
        args:
          - "cat /userconf/file.yaml; exit 0;"
        configMapMounts:
          - name: myapp
            mountPath: /userconf/
            content:
              file.yaml: |
                # this content will be mounted on
                # the pod container local filesystem at
                # /userconf/file.yaml
                test: hello world puncher at {{ .hello }}
---
apiVersion: scheduler.punchplatform.io/v2
kind: Diagram
metadata:
  name: diagram-sample
spec:
  workflow:
    begin: 1
    steps:
      - layerId: 1
        if:
          operator: or
          conditions:
            - operator: or
              nodes: [rootNode1, rootNode2]
            - operator: and
              nodes: [rootNode1, rootNode3]
        then: 
          layerId: 2
        else:
          layerId: 1
      - layerId: 2
        then:
          layerId: 3
        else:
          layerId: 2
      - layerId: 3
        then:
          layerId: 1
        else:
          layerId: 3
  layers:
    - node: rootNode1
      layerId: 1
      modelRef:
        name: appmodel
        kind: BatchApplicationModel
    - node: rootNode2
      layerId: 1
      modelRef:
        name: appmodel
        kind: BatchApplicationModel
    - node: rootNode3
      layerId: 1
      modelRef:
        name: appmodel
        kind: BatchApplicationModel
    - node: middleNode
      layerId: 2
      modelRef:
        name: appmodel
        kind: BatchApplicationModel
    - node: leafNodeLeft
      layerId: 3
      modelRef:
        name: appmodel
        kind: BatchApplicationModel
    - node: leafNodeRight
      layerId: 3
      modelRef:
        name: appmodel
        kind: BatchApplicationModel
