---
apiVersion: punchline.gitlab.thalesdigital.io/v2
kind: StreamPunchline
metadata:
  name: input-example
spec:
  containers:
    resourcesInitContainer:
      image: ghcr.io/punchplatform/resourcectl:8.0-dev
      resourcesProviderUrl: http://artifacts-service.kooker:4245
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-java:8.0-dev
  dependencies:
    - additional-punch-jar:io.github.punchplatform:punchline-java-starter-kit:1.0.0
  dag:
  - id: input
    kind: source
    type: io.github.starter.punchline.java.CustomSource
    settings:
      print: true
    out: 
    - id: processing
      table: logs
      columns:
      - name: row1
        type: string
      - name: row2
        type: string
      - name: row3
        type: string
  - id: processing
    kind: function
    type: io.github.starter.punchline.java.CustomFunction
    settings:
      print: true
    out: 
    - id: parser
      table: logs
      columns:
      - name: row1
        type: string
      - name: row2
        type: string
      - name: row3
        type: string
  - id: parser
    type: punchlet_function
    kind: function
    settings:
      punchlet_code: "{print(root);}"