#!/usr/bin/env bash -ec -o pipefail

.PHONY: prerequisites

prerequisites:
	@mkdir -p ${OUTPUT_DIR}

.PHONY: build

build:
	$(MVN) -Dmaven.repo.local=${MAVEN_LOCAL_REPOSITORY} -Drevision=${VERSION} clean install
	$(MAKE) metadata

.PHONY: docker-clean

docker-clean:
	@docker rm -f "${CONTAINER_NAME}" 2>/dev/null || true

.PHONY: help

help:
	@awk 'BEGIN {FS = ":.*##"; printf "\033[36m\033[0m\n"} /^[0-9a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-28s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)